#!/bin/bash

# TODO: Provide a less "brutal" method for clearing out containers
#
# BE CAREFUL - this scrubs you whole system's Docker files
#
# docker system prune --volumes -a

APP_NAME="compiler"
RUN_NAME="running-$APP_NAME"

case $1 in
'make')
    OPTION='run'
    COMMAND='bash ./make'
    ;;
'clean')
    OPTION='run'
    COMMAND='bash ./make clean'
    ;;
'run')
    OPTION='run'
    COMMAND='bash'
    ;;
*)
    OPTION=$1
    ;;
esac

case $OPTION in
'run')
    docker run \
        --rm \
        --interactive --tty \
        --user $(id -u):$(id -g) \
        --volume $(pwd):/usr/local/src \
        --name $RUN_NAME $APP_NAME $COMMAND
    ;;
'shell')
    docker container exec -it $RUN_NAME bash
    ;;
'build')
    docker build -t $APP_NAME ./$APP_NAME
    ;;
*)
    echo "./$APP_NAME/container [make|run|shell|build]"
    ;;
esac

